SEARCH_DIR("C:\Program Files (x86)\HiAsm\Elements\delphi\code\")
INPUT(
wprt0.o
"C:\Program Files (x86)\HiAsm\Elements\delphi\code\allres.or"
)
GROUP(
"C:\Program Files (x86)\HiAsm\Elements\delphi\code\units\libphiStr_Enum.a"
"C:\Program Files (x86)\HiAsm\Elements\delphi\code\units\libpWinList.a"
"C:\Program Files (x86)\HiAsm\Elements\delphi\code\units\libpEWinList.a"
"C:\Program Files (x86)\HiAsm\Elements\delphi\code\units\libphiCharset.a"
"C:\Program Files (x86)\HiAsm\Elements\delphi\code\units\libpWinInet.a"
"C:\Program Files (x86)\HiAsm\Elements\delphi\code\units\libphiRGN_OutlinePicture.a"
"C:\Program Files (x86)\HiAsm\Elements\delphi\code\units\libphiLayoutSpacer.a"
"C:\Program Files (x86)\HiAsm\Elements\delphi\code\units\libpWinLayout.a"
"C:\Program Files (x86)\HiAsm\Elements\delphi\code\units\libphiHintManager.a"
"C:\Program Files (x86)\HiAsm\Elements\delphi\code\units\libpDebug.a"
"C:\Program Files (x86)\HiAsm\Elements\delphi\code\units\libpWinSock.a"
"C:\Program Files (x86)\HiAsm\Elements\delphi\code\units\libpShlObj.a"
"C:\Program Files (x86)\HiAsm\Elements\delphi\code\units\libpcommdlg.a"
"C:\Program Files (x86)\HiAsm\Elements\delphi\code\units\libpShellAPI.a"
"C:\Program Files (x86)\HiAsm\Elements\delphi\code\units\libpRichEdit.a"
"C:\Program Files (x86)\HiAsm\Elements\delphi\code\units\libphiTransparentManager.a"
"C:\Program Files (x86)\HiAsm\Elements\delphi\code\units\libpMessages.a"
"C:\Program Files (x86)\HiAsm\Elements\delphi\code\units\libpWin.a"
"C:\Program Files (x86)\HiAsm\Elements\delphi\code\units\libphiMemory.a"
"C:\Program Files (x86)\HiAsm\Elements\delphi\code\units\libphiChanelToIndex.a"
"C:\Program Files (x86)\HiAsm\Elements\delphi\code\units\libphiIndexToChanel.a"
"C:\Program Files (x86)\HiAsm\Elements\delphi\code\units\libphiLabel.a"
"C:\Program Files (x86)\HiAsm\Elements\delphi\code\units\libphiWinExec.a"
"C:\Program Files (x86)\HiAsm\Elements\delphi\code\units\libphiStrCat.a"
"C:\Program Files (x86)\HiAsm\Elements\delphi\code\units\libphiDoData.a"
"C:\Program Files (x86)\HiAsm\Elements\delphi\code\units\libphiStrList.a"
"C:\Program Files (x86)\HiAsm\Elements\delphi\code\units\libphiStrCatDelim.a"
"C:\Program Files (x86)\HiAsm\Elements\delphi\code\units\libphiMultiStrData.a"
"C:\Program Files (x86)\HiAsm\Elements\delphi\code\units\libphiStrMask.a"
"C:\Program Files (x86)\HiAsm\Elements\delphi\code\units\libphiHub.a"
"C:\Program Files (x86)\HiAsm\Elements\delphi\code\units\libphiArrayEnum.a"
"C:\Program Files (x86)\HiAsm\Elements\delphi\code\units\libphiRichEdit.a"
"C:\Program Files (x86)\HiAsm\Elements\delphi\code\units\libphiEdit.a"
"C:\Program Files (x86)\HiAsm\Elements\delphi\code\units\libphiHTTP_Get.a"
"C:\Program Files (x86)\HiAsm\Elements\delphi\code\units\libphiMainForm.a"
"C:\Program Files (x86)\HiAsm\Elements\delphi\code\units\libpShare.a"
"C:\Program Files (x86)\HiAsm\Elements\delphi\code\units\libpkol.a"
"C:\Program Files (x86)\HiAsm\Elements\delphi\code\units\libpWindows.a"
"C:\Program Files (x86)\HiAsm\Elements\delphi\code\units\libphiMainForm_6D7830.a"
libpobjpas.a
libpsystem.a
"C:\Program Files (x86)\HiAsm\Elements\delphi\code\units\libpNTF.a"
)
